import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";

export interface GoogleOAuthConfig {
  clientId: string;
  clientSecret: string;
  redirectUri: string;
  sessionSecret: string;
  /** Override the Google token endpoint URL (used in E2E tests to point at a mock server). */
  tokenUrl?: string;
}

export interface GoogleTokenResponse {
  access_token: string;
  refresh_token?: string;
  id_token: string;
  expires_in: number;
  token_type: string;
  scope: string;
}

export interface GoogleIdTokenClaims {
  sub: string;
  email?: string;
  email_verified?: boolean;
  name?: string;
  picture?: string;
  iat: number;
  exp: number;
}

const GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
const GOOGLE_OAUTH_SCOPE = "openid email profile";

function upstreamError(httpStatus: number, body: unknown): Error & { statusCode: number; code: string } {
  const msg = `Google token request failed: ${httpStatus} ${JSON.stringify(body)}`;
  const err = new Error(msg) as Error & { statusCode: number; code: string };
  err.statusCode = httpStatus >= 400 && httpStatus < 500 ? 400 : 502;
  err.code = httpStatus >= 400 && httpStatus < 500 ? "oauth_client_error" : "oauth_upstream_error";
  return err;
}

// ---------------------------------------------------------------------------
// Shared HMAC helpers
// ---------------------------------------------------------------------------

function hmacSign(data: string, secret: string): string {
  return createHmac("sha256", secret).update(data).digest("hex");
}

function hmacVerify(data: string, receivedHmac: string, secret: string): boolean {
  const expectedHmac = hmacSign(data, secret);
  try {
    const expectedBuf = Buffer.from(expectedHmac, "hex");
    const receivedBuf = Buffer.from(receivedHmac, "hex");
    if (expectedBuf.length !== receivedBuf.length) return false;
    return timingSafeEqual(expectedBuf, receivedBuf);
  } catch {
    return false;
  }
}

/** Sign a session cookie value: `${userId}.${hmac(userId, secret)}` */
export function signSessionCookie(userId: string, sessionSecret: string): string {
  return `${userId}.${hmacSign(userId, sessionSecret)}`;
}

/**
 * Verify an HMAC-signed session cookie and extract the userId.
 * Returns the userId (UUID) if the signature is valid, or null if tampered/malformed.
 */
export function verifySessionCookie(cookieValue: string, sessionSecret: string): string | null {
  const dotIndex = cookieValue.lastIndexOf(".");
  if (dotIndex <= 0) return null;

  const userId = cookieValue.slice(0, dotIndex);
  const receivedHmac = cookieValue.slice(dotIndex + 1);
  if (!userId || !receivedHmac) return null;

  return hmacVerify(userId, receivedHmac, sessionSecret) ? userId : null;
}

/** Generate a stateless HMAC-signed CSRF state token: `${nonce}.${hmac}` */
export function generateState(sessionSecret: string): string {
  const nonce = randomBytes(16).toString("hex");
  return `${nonce}.${hmacSign(nonce, sessionSecret)}`;
}

/** Verify a state token generated by generateState. Returns false for any invalid or tampered input. */
export function verifyState(state: string, sessionSecret: string): boolean {
  const dotIndex = state.lastIndexOf(".");
  if (dotIndex <= 0) return false;

  const nonce = state.slice(0, dotIndex);
  const receivedHmac = state.slice(dotIndex + 1);
  if (!nonce || !receivedHmac) return false;

  return hmacVerify(nonce, receivedHmac, sessionSecret);
}

/** Build the Google OAuth2 authorization URL. */
export function buildAuthorizationUrl(config: GoogleOAuthConfig, state: string): string {
  const params = new URLSearchParams({
    client_id: config.clientId,
    redirect_uri: config.redirectUri,
    response_type: "code",
    scope: GOOGLE_OAUTH_SCOPE,
    access_type: "offline",
    prompt: "select_account",
    state,
  });
  return `${GOOGLE_AUTH_URL}?${params.toString()}`;
}

/** Exchange an authorization code for tokens. Throws on non-2xx responses. */
export async function exchangeCodeForTokens(
  config: GoogleOAuthConfig,
  code: string,
): Promise<GoogleTokenResponse> {
  const body = new URLSearchParams({
    code,
    client_id: config.clientId,
    client_secret: config.clientSecret,
    redirect_uri: config.redirectUri,
    grant_type: "authorization_code",
  });

  const res = await fetch(config.tokenUrl ?? GOOGLE_TOKEN_URL, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });

  const data = await res.json();
  if (!res.ok) throw upstreamError(res.status, data);
  return data as GoogleTokenResponse;
}

/** Exchange a refresh token for a new access token. */
export async function refreshAccessToken(
  config: GoogleOAuthConfig,
  refreshToken: string,
): Promise<{ access_token: string; expires_in: number }> {
  const body = new URLSearchParams({
    refresh_token: refreshToken,
    client_id: config.clientId,
    client_secret: config.clientSecret,
    grant_type: "refresh_token",
  });

  const res = await fetch(config.tokenUrl ?? GOOGLE_TOKEN_URL, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });

  const data = await res.json();
  if (!res.ok) throw upstreamError(res.status, data);
  return data as { access_token: string; expires_in: number };
}

/**
 * Decode an ID token's payload without signature verification.
 *
 * Signature verification is acceptable to skip here because:
 * 1. The token was received from Google's own token endpoint in exchange for a code
 * 2. The exchange was authenticated using our client_secret
 * 3. State parameter prevents CSRF
 *
 * Full JWKS-based signature verification can be added later (KZO-XX) if required.
 */
export function decodeIdTokenPayload(idToken: string): GoogleIdTokenClaims {
  const parts = idToken.split(".");
  if (parts.length !== 3) {
    throw new Error("Invalid ID token format: expected three dot-separated segments");
  }

  const payloadSegment = parts[1];
  // base64url → base64: replace - with + and _ with /
  const base64 = payloadSegment.replace(/-/g, "+").replace(/_/g, "/");
  const json = Buffer.from(base64, "base64").toString("utf8");
  return JSON.parse(json) as GoogleIdTokenClaims;
}
