-- KZO-168: FX-transfer cash-ledger producer surface.
--
-- Adds paired FX_TRANSFER_OUT / FX_TRANSFER_IN cash-ledger rows linked by a
-- shared fx_transfer_id. Operational metadata remains in audit_log.metadata.

ALTER TABLE cash_ledger_entries
  DROP CONSTRAINT IF EXISTS cash_ledger_entries_entry_type_check;

ALTER TABLE cash_ledger_entries
  ADD CONSTRAINT cash_ledger_entries_entry_type_check CHECK (
    entry_type IN (
      'TRADE_SETTLEMENT_IN',
      'TRADE_SETTLEMENT_OUT',
      'DIVIDEND_RECEIPT',
      'DIVIDEND_DEDUCTION',
      'MANUAL_ADJUSTMENT',
      'REVERSAL',
      'FX_TRANSFER_OUT',
      'FX_TRANSFER_IN'
    )
  );

ALTER TABLE cash_ledger_entries
  ADD COLUMN IF NOT EXISTS fx_transfer_id UUID;

-- Drop the two legacy generated CHECK constraints whose definitions only knew
-- the pre-KZO-168 entry type set. Constraint names are generated by Postgres,
-- so match by definition instead of relying solely on cash_ledger_entries_checkN.
-- The `LIKE '%amount%'` predicate intentionally tolerates both the pre-rename
-- form (`amount_ntd`, before migration 022) and the post-rename form
-- (`amount`); Postgres rewrites constraint definitions when columns are
-- renamed, so a previously-applied DB will match either spelling. Do not
-- tighten this predicate without also re-checking historical migration order.
DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  FOR constraint_name IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'cash_ledger_entries'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) LIKE '%TRADE_SETTLEMENT_IN%'
      AND pg_get_constraintdef(oid) LIKE '%DIVIDEND_DEDUCTION%'
      AND pg_get_constraintdef(oid) LIKE '%MANUAL_ADJUSTMENT%'
      AND pg_get_constraintdef(oid) LIKE '%REVERSAL%'
      AND pg_get_constraintdef(oid) LIKE '%amount%'
  LOOP
    EXECUTE format('ALTER TABLE cash_ledger_entries DROP CONSTRAINT %I', constraint_name);
  END LOOP;

  FOR constraint_name IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'cash_ledger_entries'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) LIKE '%related_trade_event_id IS NOT NULL%'
      AND pg_get_constraintdef(oid) LIKE '%related_dividend_ledger_entry_id IS NOT NULL%'
  LOOP
    EXECUTE format('ALTER TABLE cash_ledger_entries DROP CONSTRAINT %I', constraint_name);
  END LOOP;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_cash_ledger_entries_entry_type_amount_direction'
      AND conrelid = 'cash_ledger_entries'::regclass
  ) THEN
    ALTER TABLE cash_ledger_entries
      ADD CONSTRAINT ck_cash_ledger_entries_entry_type_amount_direction CHECK (
        (entry_type = 'TRADE_SETTLEMENT_IN' AND amount > 0)
        OR (entry_type = 'TRADE_SETTLEMENT_OUT' AND amount < 0)
        OR (entry_type = 'DIVIDEND_RECEIPT' AND amount > 0)
        OR (entry_type = 'DIVIDEND_DEDUCTION' AND amount < 0)
        OR (entry_type = 'FX_TRANSFER_OUT' AND amount < 0)
        OR (entry_type = 'FX_TRANSFER_IN' AND amount > 0)
        OR entry_type IN ('MANUAL_ADJUSTMENT', 'REVERSAL')
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_cash_ledger_entries_entry_type_links'
      AND conrelid = 'cash_ledger_entries'::regclass
  ) THEN
    ALTER TABLE cash_ledger_entries
      ADD CONSTRAINT ck_cash_ledger_entries_entry_type_links CHECK (
        (entry_type IN ('TRADE_SETTLEMENT_IN', 'TRADE_SETTLEMENT_OUT')
          AND related_trade_event_id IS NOT NULL
          AND related_dividend_ledger_entry_id IS NULL)
        OR (entry_type IN ('DIVIDEND_RECEIPT', 'DIVIDEND_DEDUCTION')
          AND related_trade_event_id IS NULL
          AND related_dividend_ledger_entry_id IS NOT NULL)
        OR (entry_type IN ('MANUAL_ADJUSTMENT', 'REVERSAL', 'FX_TRANSFER_OUT', 'FX_TRANSFER_IN')
          AND related_trade_event_id IS NULL
          AND related_dividend_ledger_entry_id IS NULL)
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_cash_ledger_entries_fx_transfer_id_entry_type'
      AND conrelid = 'cash_ledger_entries'::regclass
  ) THEN
    ALTER TABLE cash_ledger_entries
      ADD CONSTRAINT ck_cash_ledger_entries_fx_transfer_id_entry_type
      CHECK (fx_transfer_id IS NULL OR entry_type IN ('FX_TRANSFER_OUT', 'FX_TRANSFER_IN', 'REVERSAL'));
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_cash_ledger_fx_transfer_leg_originals
  ON cash_ledger_entries (fx_transfer_id, entry_type)
  WHERE fx_transfer_id IS NOT NULL
    AND reversal_of_cash_ledger_entry_id IS NULL;

-- KZO-168 lifecycle audit actions. The existing audit_log schema stores the
-- details JSON in metadata.
DO $$
BEGIN
  ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check;
  ALTER TABLE audit_log ADD CONSTRAINT audit_log_action_check CHECK (
    action IN (
      'admin_promote_cli',
      'admin_promote_startup',
      'admin_promote_first_signin',
      'admin_role_change',
      'admin_disable_user',
      'admin_enable_user',
      'admin_delete_user',
      'admin_hard_purge_user',
      'admin_invite_issued',
      'admin_invite_revoked',
      'share_granted',
      'share_revoked',
      'share_token_created',
      'share_token_revoked',
      'impersonation_start',
      'impersonation_end',
      'impersonation_blocked_write',
      'session_force_logout',
      'app_config_updated',
      'admin_fx_rates_refresh',
      'fx_transfer_created',
      'fx_transfer_updated',
      'fx_transfer_reversed'
    )
  );
END $$;
