"use client";

import type { ChatGptTransactionDraftWidgetDto } from "@vakwen/shared-types";

export function buildMockTransactionDraftWidgetData(): ChatGptTransactionDraftWidgetDto {
  return {
    mode: "review",
    title: "Import these broker statement rows into my Vakwen AI Inbox.",
    subtitle: "ChatGPT extracted structured candidates from a temporary file. Vakwen validated the candidates and returned row-level issues for review.",
    batch: {
      id: "batch-chatgpt-1",
      ownerUserId: "user-1",
      createdByUserId: "user-1",
      connectorConnectionId: "conn-chatgpt-1",
      shareId: null,
      sourceChannel: "mcp",
      status: "open",
      version: 12,
      sourceLabel: "May broker statement.pdf",
      sourceFilename: "may-broker-statement.pdf",
      note: "Connector-mediated import. Vakwen stored structured rows and capped provenance only.",
      rowCount: 5,
      unsupportedCount: 2,
      createdAt: "2026-05-27T10:10:00.000Z",
      updatedAt: "2026-05-27T10:18:00.000Z",
      archivedAt: null,
      deletedAt: null,
    },
    rows: [
      {
        id: "row-1",
        batchId: "batch-chatgpt-1",
        rowNumber: 1,
        state: "ready",
        version: 3,
        accountId: "tw-brokerage",
        accountNameInput: "TW Brokerage",
        type: "BUY",
        ticker: "2330",
        marketCode: "TW",
        quantity: 1000,
        unitPrice: 812,
        priceCurrency: "TWD",
        tradeDate: "2026-05-24",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: 1218,
        taxAmount: 0,
        feesSource: "SOURCE_PROVIDED",
        note: null,
        sourceRowRef: "pdf-row-1",
        sourceSnippet: "2330 BUY 1,000 @ 812.00 TWD",
        preflightIssues: [],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "row-2",
        batchId: "batch-chatgpt-1",
        rowNumber: 2,
        state: "ready",
        version: 4,
        accountId: "us-brokerage",
        accountNameInput: "US Brokerage",
        type: "SELL",
        ticker: "AAPL",
        marketCode: "US",
        quantity: 15,
        unitPrice: 198.4,
        priceCurrency: "USD",
        tradeDate: "2026-05-24",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: 4.95,
        taxAmount: null,
        feesSource: "SOURCE_PROVIDED",
        note: null,
        sourceRowRef: "pdf-row-2",
        sourceSnippet: "AAPL SELL 15 @ 198.40 USD",
        preflightIssues: [],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "row-3",
        batchId: "batch-chatgpt-1",
        rowNumber: 3,
        state: "needs_clarification",
        version: 2,
        accountId: null,
        accountNameInput: "AU Brokerage",
        type: "BUY",
        ticker: "BHP",
        marketCode: "AU",
        quantity: 80,
        unitPrice: 43.18,
        priceCurrency: "AUD",
        tradeDate: "2026-05-25",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: null,
        taxAmount: null,
        feesSource: "CALCULATED",
        note: null,
        sourceRowRef: "pdf-row-3",
        sourceSnippet: "BHP BUY 80 @ 43.18 AUD",
        preflightIssues: [{ message: "Account is ambiguous" }],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "row-4",
        batchId: "batch-chatgpt-1",
        rowNumber: 4,
        state: "ready",
        version: 1,
        accountId: "tw-brokerage",
        accountNameInput: "TW Brokerage",
        type: "BUY",
        ticker: "0050",
        marketCode: "TW",
        quantity: 3000,
        unitPrice: 186.75,
        priceCurrency: "TWD",
        tradeDate: "2026-05-25",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: 840,
        taxAmount: 0,
        feesSource: "SOURCE_PROVIDED",
        note: null,
        sourceRowRef: "pdf-row-4",
        sourceSnippet: "0050 BUY 3,000 @ 186.75 TWD",
        preflightIssues: [],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "row-5",
        batchId: "batch-chatgpt-1",
        rowNumber: 5,
        state: "invalid",
        version: 2,
        accountId: "us-brokerage",
        accountNameInput: "US Brokerage",
        type: "BUY",
        ticker: "NVDA",
        marketCode: "US",
        quantity: 10,
        unitPrice: 138.12,
        priceCurrency: "USD",
        tradeDate: "2026-05-25",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: 0,
        taxAmount: 9.99,
        feesSource: "SOURCE_PROVIDED",
        note: null,
        sourceRowRef: "pdf-row-5",
        sourceSnippet: "NVDA BUY 10 @ 138.12 USD",
        preflightIssues: [{ message: "Source fees conflict with account defaults" }],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
    ],
    unsupportedItems: [
      {
        id: "unsupported-1",
        batchId: "batch-chatgpt-1",
        rowNumber: 6,
        category: "cash_movement",
        reason: "Cash transfer rows remain audit-only in this phase.",
        sourceSnippet: "Deposit +50,000 TWD",
        createdAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "unsupported-2",
        batchId: "batch-chatgpt-1",
        rowNumber: 7,
        category: "dividend",
        reason: "Dividend rows are not draftable in this workflow.",
        sourceSnippet: "Dividend AAPL +12.40 USD",
        createdAt: "2026-05-27T10:18:00.000Z",
      },
    ],
    selectedRowIds: ["row-1", "row-2", "row-4"],
    grossValueText: "TWD 1.38M + USD 4.36K",
    deepLinkUrl: "/transactions?tab=ai-inbox&batch=batch-chatgpt-1&context=user-1",
    provenance: {
      sourceLabel: "May broker statement.pdf",
      sourceFilename: "may-broker-statement.pdf",
      sourceSummary: "Vakwen received structured candidates, capped snippets, row mappings, and provenance metadata only. The temporary file stays in ChatGPT unless the user explicitly opts into its file library.",
      sourceChannelLabel: "ChatGPT connector import",
      structuredCandidatesOnly: true,
      snippetCharacterCap: 500,
      rowMappingCount: 7,
    },
    permissions: {
      canEdit: true,
      canArchive: true,
      canDelete: true,
      canPost: true,
      writeScopeGranted: true,
      requiresWriteReconsent: false,
      adminWritePolicyEnabled: true,
    },
    auditPreview: [
      { tone: "info", message: "Created by the ChatGPT connector from structured candidates." },
      { tone: "success", message: "Source snippets are capped at 500 characters per row." },
      { tone: "warning", message: "Two rows still need clarification before they can post." },
    ],
    postingResult: null,
    tools: {
      refresh: "get_transaction_draft_batch_component",
      updateRow: "update_transaction_draft_rows",
      excludeRows: "exclude_transaction_draft_rows",
      reincludeRows: "reinclude_transaction_draft_rows",
      rejectRows: "reject_transaction_draft_rows",
      archiveBatch: "archive_transaction_draft_batch",
      deleteBatch: "delete_unconfirmed_transaction_draft_batch",
      postRows: "post_transaction_draft_rows",
    },
  };
}
