"use client";

import type { ChatGptTransactionDraftWidgetDto } from "@vakwen/shared-types";
import type { ChatGptWidgetAccountOption } from "./chatGptWidgetTypes";

export function buildMockTransactionDraftWidgetData(): ChatGptTransactionDraftWidgetDto {
  const accountOptions: ChatGptWidgetAccountOption[] = [
    { id: "tw-brokerage", name: "Cathay TW Brokerage", defaultCurrency: "TWD", accountType: "broker", feeProfileName: "TW Equity Default", status: "active" },
    { id: "us-brokerage", name: "USD Brokerage", defaultCurrency: "USD", accountType: "broker", feeProfileName: "US Equity Default", status: "active" },
    { id: "cash-wallet", name: "Cash Wallet", defaultCurrency: "USD", accountType: "wallet", feeProfileName: "Cash Wallet Fees", status: "active" },
  ];
  const accounts = accountOptions.map((account) => ({
    id: account.id,
    name: account.name,
    defaultCurrency: account.defaultCurrency ?? "TWD",
    accountType: account.accountType ?? "broker",
    feeProfileId: `${account.id}-fees`,
    feeProfileName: account.feeProfileName ?? null,
    status: "active" as const,
    deletedAt: null,
    liveBalance: [],
  }));
  const postingPreview: ChatGptTransactionDraftWidgetDto["postingPreview"] = {
    batchId: "batch-chatgpt-1",
    batchVersion: 12,
    selectedRowIds: ["row-1", "row-2"],
    rows: [
      {
        rowId: "row-1",
        rowNumber: 1,
        accountId: "tw-brokerage",
        accountName: "Cathay TW Brokerage",
        accountType: "broker",
        accountDefaultCurrency: "TWD",
        ticker: "2330.TW",
        marketCode: "TW",
        type: "BUY",
        quantity: 1000,
        unitPrice: 812,
        priceCurrency: "TWD",
        tradeDate: "2026-05-24",
        grossValueAmount: 812_000,
        commissionAmount: 0,
        taxAmount: 10,
        calculatedCommissionAmount: 1_160,
        calculatedTaxAmount: 10,
        feesSource: "MANUAL",
        netCashImpactAmount: -812_010,
        suggestions: ["Confirm the manual fee override before posting; Vakwen will preserve the submitted values."],
        sourceSnippet: "2330 BUY 1,000 @ 812.00 TWD",
        warnings: ["Manual zero commission differs from calculated fee"],
      },
      {
        rowId: "row-2",
        rowNumber: 2,
        accountId: "us-brokerage",
        accountName: "USD Brokerage",
        accountType: "broker",
        accountDefaultCurrency: "USD",
        ticker: "AAPL",
        marketCode: "US",
        type: "SELL",
        quantity: 15,
        unitPrice: 198.4,
        priceCurrency: "USD",
        tradeDate: "2026-05-24",
        grossValueAmount: 2_976,
        commissionAmount: 4.95,
        taxAmount: 0,
        calculatedCommissionAmount: 4.95,
        calculatedTaxAmount: 0,
        feesSource: "SOURCE_PROVIDED",
        netCashImpactAmount: 2_971.05,
        suggestions: [],
        sourceSnippet: "AAPL SELL 15 @ 198.40 USD",
        warnings: [],
      },
    ],
    groups: [
      {
        accountId: "tw-brokerage",
        accountName: "Cathay TW Brokerage",
        currency: "TWD",
        rowCount: 1,
        totalGrossBuyAmount: 812_000,
        totalGrossSellAmount: 0,
        totalCommissionAmount: 0,
        totalTaxAmount: 10,
        netCashImpactAmount: -812_010,
      },
      {
        accountId: "us-brokerage",
        accountName: "USD Brokerage",
        currency: "USD",
        rowCount: 1,
        totalGrossBuyAmount: 0,
        totalGrossSellAmount: 2_976,
        totalCommissionAmount: 4.95,
        totalTaxAmount: 0,
        netCashImpactAmount: 2_971.05,
      },
    ],
    warnings: ["Posting preview is server-computed before confirmation."],
    suggestions: ["Confirm the manual fee override before posting; Vakwen will preserve the submitted values."],
    typedPhraseRequired: "POST 3 TRADES",
  };
  const widget = {
    mode: "review",
    title: "Import these broker statement rows into my Vakwen AI Inbox.",
    subtitle: "ChatGPT extracted structured candidates from a temporary file. Vakwen validated the candidates and returned row-level issues for review.",
    batch: {
      id: "batch-chatgpt-1",
      ownerUserId: "user-1",
      createdByUserId: "user-1",
      connectorConnectionId: "conn-chatgpt-1",
      shareId: null,
      sourceChannel: "mcp",
      status: "open",
      version: 12,
      sourceLabel: "May broker statement.pdf",
      sourceFilename: "may-broker-statement.pdf",
      note: "Connector-mediated import. Vakwen stored structured rows and capped provenance only.",
      rowCount: 5,
      unsupportedCount: 2,
      createdAt: "2026-05-27T10:10:00.000Z",
      updatedAt: "2026-05-27T10:18:00.000Z",
      archivedAt: null,
      deletedAt: null,
    },
    rows: [
      {
        id: "row-1",
        batchId: "batch-chatgpt-1",
        rowNumber: 1,
        state: "ready",
        version: 3,
        accountId: "tw-brokerage",
        accountName: "Cathay TW Brokerage",
        accountNameInput: "TW Brokerage",
        type: "BUY",
        ticker: "2330",
        marketCode: "TW",
        quantity: 1000,
        unitPrice: 812,
        priceCurrency: "TWD",
        tradeDate: "2026-05-24",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: 0,
        taxAmount: 10,
        feesSource: "MANUAL",
        note: null,
        sourceRowRef: "pdf-row-1",
        sourceSnippet: "2330 BUY 1,000 @ 812.00 TWD",
        preflightIssues: [],
        warnings: [{ message: "Manual zero commission differs from calculated fee" }],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "row-2",
        batchId: "batch-chatgpt-1",
        rowNumber: 2,
        state: "ready",
        version: 4,
        accountId: "us-brokerage",
        accountName: "USD Brokerage",
        accountNameInput: "US Brokerage",
        type: "SELL",
        ticker: "AAPL",
        marketCode: "US",
        quantity: 15,
        unitPrice: 198.4,
        priceCurrency: "USD",
        tradeDate: "2026-05-24",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: 4.95,
        taxAmount: null,
        feesSource: "SOURCE_PROVIDED",
        note: null,
        sourceRowRef: "pdf-row-2",
        sourceSnippet: "AAPL SELL 15 @ 198.40 USD",
        preflightIssues: [],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "row-3",
        batchId: "batch-chatgpt-1",
        rowNumber: 3,
        state: "needs_clarification",
        version: 2,
        accountId: null,
        accountName: null,
        accountNameInput: "AU Brokerage",
        type: "BUY",
        ticker: "BHP",
        marketCode: "AU",
        quantity: 80,
        unitPrice: 43.18,
        priceCurrency: "AUD",
        tradeDate: "2026-05-25",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: null,
        taxAmount: null,
        feesSource: "CALCULATED",
        note: null,
        sourceRowRef: "pdf-row-3",
        sourceSnippet: "BHP BUY 80 @ 43.18 AUD",
        preflightIssues: [{ message: "Account is ambiguous" }],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "row-4",
        batchId: "batch-chatgpt-1",
        rowNumber: 4,
        state: "ready",
        version: 1,
        accountId: "tw-brokerage",
        accountName: "Cathay TW Brokerage",
        accountNameInput: "TW Brokerage",
        type: "BUY",
        ticker: "0050",
        marketCode: "TW",
        quantity: 3000,
        unitPrice: 186.75,
        priceCurrency: "TWD",
        tradeDate: "2026-05-25",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: 840,
        taxAmount: 0,
        feesSource: "SOURCE_PROVIDED",
        note: null,
        sourceRowRef: "pdf-row-4",
        sourceSnippet: "0050 BUY 3,000 @ 186.75 TWD",
        preflightIssues: [],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "row-5",
        batchId: "batch-chatgpt-1",
        rowNumber: 5,
        state: "invalid",
        version: 2,
        accountId: "us-brokerage",
        accountName: "USD Brokerage",
        accountNameInput: "US Brokerage",
        type: "BUY",
        ticker: "NVDA",
        marketCode: "US",
        quantity: 10,
        unitPrice: 138.12,
        priceCurrency: "USD",
        tradeDate: "2026-05-25",
        tradeTimestamp: null,
        bookingSequence: null,
        isDayTrade: false,
        commissionAmount: 0,
        taxAmount: 9.99,
        feesSource: "SOURCE_PROVIDED",
        note: null,
        sourceRowRef: "pdf-row-5",
        sourceSnippet: "NVDA BUY 10 @ 138.12 USD",
        preflightIssues: [{ message: "Source fees conflict with account defaults" }],
        warnings: [],
        confirmedTradeEventId: null,
        confirmedAt: null,
        updatedAt: "2026-05-27T10:18:00.000Z",
      },
    ],
    unsupportedItems: [
      {
        id: "unsupported-1",
        batchId: "batch-chatgpt-1",
        rowNumber: 6,
        category: "cash_movement",
        reason: "Cash transfer rows remain audit-only in this phase.",
        sourceSnippet: "Deposit +50,000 TWD",
        createdAt: "2026-05-27T10:18:00.000Z",
      },
      {
        id: "unsupported-2",
        batchId: "batch-chatgpt-1",
        rowNumber: 7,
        category: "dividend",
        reason: "Dividend rows are not draftable in this workflow.",
        sourceSnippet: "Dividend AAPL +12.40 USD",
        createdAt: "2026-05-27T10:18:00.000Z",
      },
    ],
    selectedRowIds: ["row-1", "row-2", "row-4"],
    accounts,
    grossValueText: "TWD 1.38M + USD 4.36K",
    deepLinkUrl: "/transactions?tab=ai-inbox&batch=batch-chatgpt-1&context=user-1",
    postingPreview,
    suggestions: ["Confirm the manual fee override before posting; Vakwen will preserve the submitted values."],
    provenance: {
      sourceLabel: "May broker statement.pdf",
      sourceFilename: "may-broker-statement.pdf",
      sourceSummary: "Vakwen received structured candidates, capped snippets, row mappings, and provenance metadata only. The temporary file stays in ChatGPT unless the user explicitly opts into its file library.",
      sourceChannelLabel: "ChatGPT connector import",
      structuredCandidatesOnly: true,
      snippetCharacterCap: 500,
      rowMappingCount: 7,
    },
    permissions: {
      canEdit: true,
      canArchive: true,
      canDelete: true,
      canPost: true,
      writeScopeGranted: true,
      requiresWriteReconsent: false,
      adminWritePolicyEnabled: true,
    },
    auditPreview: [
      { tone: "info", message: "Created by the ChatGPT connector from structured candidates." },
      { tone: "success", message: "Source snippets are capped at 500 characters per row." },
      { tone: "warning", message: "Two rows still need clarification before they can post." },
    ],
    postingResult: null,
    tools: {
      refresh: "get_transaction_draft_batch_component",
      previewPosting: "get_transaction_draft_posting_preview",
      updateRow: "update_transaction_draft_rows",
      excludeRows: "exclude_transaction_draft_rows",
      reincludeRows: "reinclude_transaction_draft_rows",
      rejectRows: "reject_transaction_draft_rows",
      archiveBatch: "archive_transaction_draft_batch",
      deleteBatch: "delete_unconfirmed_transaction_draft_batch",
      postRows: "post_transaction_draft_rows",
    },
  } satisfies ChatGptTransactionDraftWidgetDto;
  return widget;
}
